hvim: use wrapper

diff --git a/bin/hvim b/bin/hvim
--- a/bin/hvim
+++ b/bin/hvim
@@ -2,19 +2,33 @@
 
 vimdir="$HOME/.vim"
 
-pipePath="$vimdir/hvim-pipe"
 logPath="$vimdir/hvim-log"
 
-myPath="$(pwd)/$0"
-myDir="$(dirname "$myPath")"
-bindir="$myDir"
+#copy-pasted from http://stackoverflow.com/a/246128/2435506
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+  SOURCE="$(readlink "$SOURCE")"
+  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+done
 
-#if [ -p "$pipePath" ]; then
-#    rm "$pipePath"
-#fi
+DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
-mkfifo "$pipePath"
+myPath="$SOURCE"
+myDir="$DIR"
+binDir="$myDir"
 
-#./hvim-listener "$pipePath" >> "$logPath" &
-vim -w "$pipePath" $*
-rm "$pipePath"
+wrapperPath="$myDir/wrapper"
+vimPath=$(which vim)
+
+if [ ! -x "$wrapperPath" ]; then
+    echo "Cannot execute $wrapperPath" > /dev/stderr
+    exit 1
+fi
+
+if [ ! -x "$vimPath" ]; then
+    echo "Cannot execute $vimPath" > /dev/stderr
+    exit 1
+fi
+
+"$wrapperPath" "$logPath" "$vimPath" $*
